version: '2.4'

services:
  django:
    container_name: ${COMPOSE_PROJECT_NAME}_django
    image: ${COMPOSE_PROJECT_NAME}_python
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
    networks:
      - piklematestnetwork
    volumes:
      - ./src:/app
    env_file:
      - ./.env
    ports:
      - "7000:7000"
    expose:
      - "7000"
    command: python3 manage.py runserver 0.0.0.0:7000
    depends_on:
      - postgres_db

  postgres_db:
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    hostname: postgres
    image: postgres:14.1-alpine
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    ports:
      - "5434:5432"
    networks:
      - piklematestnetwork
    volumes:
      - piklemtestadb:/var/lib/postgres_14/data
    environment:
      - POSTGRES_DB=piklema
      - POSTGRES_USER=piklema
      - POSTGRES_PASSWORD=piklema
      - POSTGRES_PORT=5432

networks:
  piklematestnetwork:

volumes:
  piklemtestadb:
