# Generated by Django 3.2.8 on 2022-11-07 11:49

from django.db import migrations

USER_ID = 1
DEVICES_COUNT = 3
TAGS_COUNT = 3


def device_code(apps, *_):
    Device = apps.get_model('telemetry.Device')
    bulk_data = []
    for i in range(DEVICES_COUNT):
        bulk_data.append(
            Device(
                name=f'device_{i}',
                user_id=USER_ID,
            )
        )
    Device.objects.bulk_create(bulk_data)


def device_reverse_code(apps, *_):
    Device = apps.get_model('telemetry.Device')
    Device.objects.all().delete()


def tag_code(apps, *_):
    Device = apps.get_model('telemetry.Device')
    Tag = apps.get_model('telemetry.Tag')
    device_list = Device.objects.values_list('id', flat=True)
    bulk_data = []
    for device_id in device_list:
        for i in range(TAGS_COUNT):
            bulk_data.append(
                Tag(
                    name=f'tag_{i}',
                    device_id=device_id,
                    ratio=0.5,
                )
            )
    Tag.objects.bulk_create(bulk_data)


def tag_reverse_code(apps, *_):
    Tag = apps.get_model('telemetry.Tag')
    Tag.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(device_code, device_reverse_code),
        migrations.RunPython(tag_code, tag_reverse_code),
    ]
