# Generated by Django 3.2.8 on 2022-11-10 18:26

from django.contrib.auth import get_user_model
from django.db import migrations

USERNAME = 'root'
EMAIL = 'some@email.ru'
PASSWORD = '123'


def code(apps, *_):
    user_model = get_user_model()
    user_model.objects.create_superuser(
        username=USERNAME,
        email=EMAIL,
        password=PASSWORD,
    )


def reverse_code(apps, *_):
    user_model = get_user_model()
    user_model.objects.filter(username=USERNAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code, reverse_code, atomic=True)
    ]
