# Generated by Django 3.2.8 on 2022-11-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagvalue',
            name='timestamp',
            field=models.DateTimeField(verbose_name='timestamp'),
        ),
    ]
